"""Generate responsive WebP versions of the homepage and primary model images."""

from __future__ import annotations

import re
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
CONSTANTS = ROOT / "src" / "constants.ts"
MANIFEST = ROOT / "src" / "lib" / "responsiveImageManifest.ts"
TARGET_WIDTHS = (640, 1024, 1536)
HOME_HERO = "/images/modular-capsule-forest-retreat-hero-v2.png"


def project_images() -> list[str]:
    source = CONSTANTS.read_text(encoding="utf-8")
    images = set(re.findall(r"\bimage:\s*'(/images/[^']+)'", source))
    images.add(HOME_HERO)
    return sorted(images)


def output_path(source: str, width: int) -> Path:
    relative = Path(source.replace("/images/", "", 1))
    return PUBLIC / "images" / "responsive" / relative.with_suffix("").parent / f"{relative.stem}-{width}.webp"


def main() -> None:
    manifest: dict[str, list[int]] = {}
    sources = project_images()

    for source in sources:
        original = PUBLIC / source.lstrip("/")
        if not original.exists():
            raise FileNotFoundError(f"Referenced primary model image is missing: {source}")

        with Image.open(original) as image:
            image = ImageOps.exif_transpose(image)
            original_width, original_height = image.size
            widths = sorted({width for width in TARGET_WIDTHS if width < original_width} | {original_width})
            manifest[source] = widths

            for width in widths:
                height = round(original_height * width / original_width)
                resized = image if width == original_width else image.resize((width, height), Image.Resampling.LANCZOS)
                destination = output_path(source, width)
                destination.parent.mkdir(parents=True, exist_ok=True)
                resized.save(destination, "WEBP", quality=82, method=6)

    entries = "\n".join(
        f'  "{source}": [{", ".join(map(str, widths))}],' for source, widths in manifest.items()
    )
    MANIFEST.write_text(
        "// Generated by scripts/generate-responsive-images.py. Do not edit by hand.\n"
        "export const RESPONSIVE_IMAGE_WIDTHS: Record<string, readonly number[]> = {\n"
        f"{entries}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"Generated {sum(len(widths) for widths in manifest.values())} WebP files for {len(sources)} primary images.")


if __name__ == "__main__":
    main()
